Diamond singularity armor
insertStringHere/MineBound pull request #101
Opened 2023-02-26 08:59 UTC by solidwaterslayer

2023-02-26 09:37 UTC, MattKirchh requested changes

2023-02-26 09:37 UTC, MattKirchh commented on src/main/resources/data/minebound/recipes/gilded_diamond_helmet.json
> +    "   "
Remove this third and empty empty string from all the helmet recipes, even the ones that were already done. Seems like they were missed in review.

2023-02-26 09:37 UTC, MattKirchh commented on src/main/resources/assets/minebound/lang/en_us.json
> +  "item.minebound.gilded_diamond_helmet": "Gilded Diamond Helmet",
Missing Myrial Singularity entries.

2023-02-26 09:37 UTC, MattKirchh commented on src/main/java/com/mineboundteam/minebound/registry/ItemRegistry.java
> +    public static final RegistryObject<Item> MYRIAL_SINGULARITY_HELMET = ITEMS.register("myrial_singularity_helmet", () -> new MyrialArmorItem(ArmorMaterials.MYRIAL_SINGULARITY, EquipmentSlot.HEAD, n
Singularity armor should be registered after the Synergy armor.

2023-02-28 03:15 UTC, insertStringHere requested changes

2023-02-28 03:15 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
> +    GILDED_DIAMOND(33, new int[] { 3, 6, 8, 3 }, 8, SoundEvents.ARMOR_EQUIP_DIAMOND, 2.5F, 0,  Ingredient.of(ItemRegistry.GILDED_DIAMOND_INGOT.get())),
make enchantability follow the tools and check those defense values. They shouldn't be copy and pasted. Both should also have some knockback resistance like .1 for gilded diamond and .3 for myrial. Myrial should also have higher toughness, like 3.5-4

2023-02-28 03:15 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
> +    MYRIAL_SINGULARITY(0, new int[] { 3, 6, 8, 3 }, 0, SoundEvents.ARMOR_EQUIP_NETHERITE, 0f, 0f, null),
This needs the armor toughness and knockback resistance of netherite

2023-02-28 03:21 UTC, MattKirchh commented
Also, resolve merge conflicts.

2023-02-28 03:46 UTC, MattKirchh approved these changes

2023-02-28 03:47 UTC, insertStringHere approved these changes

2023-02-28 03:48 UTC, merged