MBM-48 feature | add magelight
insertStringHere/MineBound pull request #104
Opened 2023-02-28 03:06 UTC by solidwaterslayer

2023-02-28 03:16 UTC, MattKirchh commented
The Magelight needs a custom block class the implements the functionality from `onPlace` and `tick` from `BoomButton.java` in this PR (#17). You can leave it as scheduled for 60 ticks. That can be modified once it's implemented with it's associated spell.

2023-03-03 22:14 UTC, MattKirchh approved these changes

2023-03-05 20:01 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/registry/BlockRegistry.java
> +    public static final RegistryObject<Block> MAGELIGHT = BLOCKS.register("magelight", () -> new Magelight(Properties.copy(Blocks.GLOWSTONE)));
I'm not sure if this should make the glowstone sound when breaking

2023-03-05 20:38 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/registry/BlockRegistry.java
> +    public static final RegistryObject<Block> MAGELIGHT = BLOCKS.register("magelight", () -> new Magelight(Properties.copy(Blocks.GLOWSTONE)));
preferably anything not "hard", like wool or dry sponge. I don't know, though

2023-03-08 20:54 UTC, insertStringHere approved these changes

2023-03-14 19:55 UTC, MattKirchh requested changes

2023-03-14 19:55 UTC, MattKirchh commented on src/main/java/com/mineboundteam/minebound/block/registry/BlockRegistry.java
> +    public static final RegistryObject<Block> MAGELIGHT = BLOCKS.register("magelight", () -> new Magelight(BlockBehaviour.Properties.of(Material.WOOL, MaterialColor.NONE).lightLevel((blockState) -> 1
Magelight should not be in between the alloy blocks.

2023-04-05 23:54 UTC, MattKirchh approved these changes

2023-04-07 19:05 UTC, merged