Mbm 353 myrial sword
insertStringHere/MineBound pull request #160
Opened 2023-04-20 16:22 UTC by solidwaterslayer

2023-04-21 15:49 UTC, insertStringHere requested changes

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +            entityHitResult.getEntity().hurt(DamageSource.MAGIC, 7);
Should probably be physical damage, or whatever we have myrial machete deals

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +    public void tick() {
should probably make sure player isn't out of range and automatically return if they are

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +    public void tick() {
Also there should probably be a failsafe for when returning in case it can't get to the player after a few seconds

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/MyrialSword.java
> +    public @NotNull InteractionResultHolder<ItemStack> use(@NotNull Level level, @NotNull Player player, @NotNull InteractionHand interactionHand) {
Not sure if it's possible, but the intention was to have the sword track the user _while using_ it. The toggle is fine if the lerp for player look and the translation is too difficult at the moment; having a stationary spinning blade of death is cool too lol

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +public class MyrialSwordEntity extends ThrowableItemProjectile {
Should not pass through blocks

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/MyrialSword.java
Needs to be removed from inventory when unselected. Possibly extend MyrialMachete, or merge with MyrialMachete adding a parameters to the constructor for the entity to spawn (null means no throw capability)

2023-04-21 15:49 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/MyrialSwordVacuum.java
Same with this; needs to remove from inventory and delete the sword entity if not selected

2023-04-23 00:01 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +public class MyrialSwordEntity extends ThrowableItemProjectile {
Now it does not stay out when it collides with blocks; should hover at that location when it hits a block

2023-04-23 00:01 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/MyrialSword.java
> +    public @NotNull InteractionResultHolder<ItemStack> use(@NotNull Level level, @NotNull Player player, @NotNull InteractionHand interactionHand) {
Movement is choppy, is there a way to smooth it?

2023-05-08 15:31 UTC, insertStringHere requested changes

2023-05-08 15:31 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/entity/MyrialSwordEntity.java
> +    public void move() {
After doing Telekinetic defensive, I've learned Minecraft already has a bunch of Move methods for entities. You should be able to use the existing `move` method alongside the velocity. See the Telekinetic Defensive code for an example

2023-05-08 15:31 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/MyrialSword.java
> +        super(tier, attackDamageModifier, attackSpeedModifier, properties, MagicConfigRegistry.TELEKINETIC_OFFENSIVE_1);
Config should be an argument

2023-05-12 07:16 UTC, MattKirchh commented
Currently missing the following:

- `MyrialSwordEntity` model
- Myrial Sword Vacuum texture

And a TODO for me:
- Update hover text for Tier Two

2023-05-13 17:44 UTC, mnt43 approved these changes
I'm not sure if we still want to do this but I think the plan was to have the machette, sword, and chakrum be the same class and have configs to turn on and off certain features.

2023-05-13 17:44 UTC, mnt43 approved these changes
I'm not sure if we still want to do this but I think the plan was to have the machette, sword, and chakrum be the same class and have configs to turn on and off certain features.

2023-05-13 17:44 UTC, mnt43 approved these changes
I'm not sure if we still want to do this but I think the plan was to have the machette, sword, and chakrum be the same class and have configs to turn on and off certain features.

2023-05-14 00:06 UTC, MattKirchh commented
> Currently missing the following:
> 
>     * `MyrialSwordEntity` model
> 
>     * ~Myrial Sword Placeholder texture~ Done
> 
> 
> And a TODO for me:
> 
>     * ~Update hover text for Tier Two~ Done

Just missing a model now. I have no idea how to do that.

2023-05-15 22:05 UTC, insertStringHere commented
> > Currently missing the following:
> > ```
> > * `MyrialSwordEntity` model
> > 
> > * ~Myrial Sword Placeholder texture~ Done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And a TODO for me:
> > ```
> > * ~Update hover text for Tier Two~ Done
> > ```
> 
> Just missing a model now. I have no idea how to do that.

We'll add a custom model for it; for now, this is good

2023-05-15 22:05 UTC, insertStringHere approved these changes

2023-05-15 22:06 UTC, merged