MBM-46 added myrial locker
insertStringHere/MineBound pull request #38
Opened 2023-01-19 02:07 UTC by aat79

2023-01-19 02:14 UTC, MattKirchh commented
The `myrial_locker.json` in models/block needs the same treatment that `myrial_steel_block.json` got. Replace the `minecraft:` with `minebound:` and it needs a `myrial_locker.json` in models/item. Looks like this got missed in review.

2023-01-19 02:56 UTC, MattKirchh approved these changes

2023-01-19 05:02 UTC, insertStringHere requested changes

2023-01-19 05:02 UTC, insertStringHere commented on src/main/resources/assets/minebound/blockstates/myrial_locker.json
> +      "model": "minebound:block/myrial_locker"
this needs facing variants; it's not a uniform block

2023-01-19 06:08 UTC, insertStringHere reviewed
Made updates to directional blocks

2023-01-19 06:09 UTC, insertStringHere submitted a review, later dismissed

2023-01-19 06:33 UTC, MattKirchh submitted a review, later dismissed

2023-01-19 22:07 UTC, MattKirchh commented on src/main/resources/assets/minebound/models/block/myrial_locker.json
>  }
How come you reverted Mason's changes here? `orientable` seems to work.

2023-01-20 02:47 UTC, MattKirchh approved these changes

2023-01-20 02:59 UTC, solidwaterslayer approved these changes

2023-01-20 03:13 UTC, merged