MBM-263 feature | add myrial suit armor
insertStringHere/MineBound pull request #64
Opened 2023-02-04 15:53 UTC by solidwaterslayer

2023-02-04 23:44 UTC, insertStringHere requested changes

2023-02-04 23:44 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
> +    ArmorMaterials(int pDurabilityMultiplier, int[] pSlotProtections, int pEnchantmentValue, SoundEvent pSound, float pToughness, float pKnockbackResistance, Ingredient pRepairIngredient) {
these changes are unnecessary

2023-02-04 23:44 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/armor/MyrialArmorItem.java
> +        data.addAnimationController(new AnimationController<>(this, getDescriptionId(), 20, this::predicate));
Why did you remove this?

2023-02-04 23:44 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
>  import net.minecraft.world.entity.EquipmentSlot;
Please rename MYRIAL_SUIT to MYRIAL_EFFIGY and then add a new ArmorMaterial for the suit; those are not the right defense values for the suit

2023-02-06 00:12 UTC, solidwaterslayer commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
> +    ArmorMaterials(int pDurabilityMultiplier, int[] pSlotProtections, int pEnchantmentValue, SoundEvent pSound, float pToughness, float pKnockbackResistance, Ingredient pRepairIngredient) {
Intellij told me to remove this.

2023-02-06 00:12 UTC, solidwaterslayer commented on src/main/java/com/mineboundteam/minebound/item/armor/MyrialArmorItem.java
> +        data.addAnimationController(new AnimationController<>(this, getDescriptionId(), 20, this::predicate));
Intellij told me to remove this.

2023-02-06 00:45 UTC, insertStringHere commented on src/main/java/com/mineboundteam/minebound/item/ArmorMaterials.java
> +    MYRIAL_SUIT(15, new int[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, 0f, 0f, null);
Durability modifier and enchantability should be 0; this armor has custom durability and cannot be enchanted

2023-02-07 00:27 UTC, MattKirchh commented
There was an issue with the path to the armor textures in `MyrialArmorModel`. Since it is the last night of the sprint, I am just going to push that fix to this branch and approve.

2023-02-07 00:28 UTC, MattKirchh approved these changes

2023-02-07 00:46 UTC, insertStringHere approved these changes

2023-02-07 00:49 UTC, merged